### ISSUE TITLE
rz-hash <file> coredumps

### ISSUE THREAD

**Issue by gkamathe** [rizinorg/rizin#1145]
I was trying out few commands from below guide

https://book.rizin.re/first_steps/overview.html

rz-hash in particular, however the command core dumps

```
$ rz-hash file
```

Version info

```
$ rizin -v
rizin 0.3.0-git @ linux-x86-64
commit: c17a23a9139be19283d288b02cb328c6939fab6d, build: 2021-05-18__13:44:14
$
```

Reproducer

```
$ rz-hash /bin/ls
Segmentation fault (core dumped)
$ ls
core.21493
$ file core.21493 
core.21493: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'rz-hash /bin/ls', real uid: 1000, effective uid: 1000, real gid: 1000, effective gid: 1000, execfn: '/usr/local/bin/rz-hash', platform: 'x86_64'
$
```

backtrace

```
$ which rz-hash
/usr/local/bin/rz-hash
$ gdb -q /usr/local/bin/rz-hash ./core.21493
Reading symbols from /usr/local/bin/rz-hash...
[New LWP 21493]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `rz-hash /bin/ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f564679c881 in __strstr_sse2_unaligned () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.32-4.fc33.x86_64
(gdb) bt
#0  0x00007f564679c881 in __strstr_sse2_unaligned () from /lib64/libc.so.6
#1  0x00007f56468f0ad0 in rz_hash_parse_cmdline (ctx=0x7fff9ad63f40, argv=0x7fff9ad640f8, argc=<optimized out>) at ../librz/main/rz-hash.c:394
#2  rz_main_rz_hash (argc=<optimized out>, argv=0x7fff9ad640f8) at ../librz/main/rz-hash.c:1168
#3  0x00007f564671b1e2 in __libc_start_main () from /lib64/libc.so.6
#4  0x000000000040107e in _start ()
(gdb) bt full
#0  0x00007f564679c881 in __strstr_sse2_unaligned () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f56468f0ad0 in rz_hash_parse_cmdline (ctx=0x7fff9ad63f40, argv=0x7fff9ad640f8, argc=<optimized out>) at ../librz/main/rz-hash.c:394
        seed = 0x0
        key = 0x0
        opt = {
          err = 1,
          ind = 1,
          opt = 0,
          reset = 0,
          arg = 0x0,
          argc = 2,
          argv = 0x7fff9ad640f8,
          ostr = 0x7f56468fb5a0 "jD:e:vE:a:i:I:S:K:s:x:b:nBhf:t:kLqc:"
        }
        c = <optimized out>
        seed = <optimized out>
        key = <optimized out>
        opt = {
          err = <optimized out>,
          ind = <optimized out>,
          opt = <optimized out>,
          reset = <optimized out>,
          arg = <optimized out>,
          argc = <optimized out>,
          argv = <optimized out>,
          ostr = <optimized out>
        }
        c = <optimized out>
        __func__ = "rz_hash_parse_cmdline"
        i = <optimized out>
        len = <optimized out>
#2  rz_main_rz_hash (argc=<optimized out>, argv=0x7fff9ad640f8) at ../librz/main/rz-hash.c:1168
        result = 1
        ctx = {
          as_prefix = false,
          little_endian = false,
          show_blocks = false,
          use_stdin = false,
          algorithm = 0x0,
          compare = 0x0,
          input = 0x0,
          iv = 0x0,
          files = 0x1fdf2a0,
          key = {
            buf = 0x0,
            len = 0
          },
          seed = {
            buf = 0x0,
            len = 0
          },
          mode = RZ_HASH_MODE_STANDARD,
          offset = {
            from = 0,
            to = 0
          },
          operation = RZ_HASH_OP_UNKNOWN,
          nfiles = 1,
          block_size = 0,
          iterate = 0,
          pj = 0x0
        }
#3  0x00007f564671b1e2 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#4  0x000000000040107e in _start ()
No symbol table info available.
(gdb)
``` 

Seems the problem lies here ?

```
(gdb) break librz/main/rz-hash.c:394
No source file named librz/main/rz-hash.c.
Breakpoint 1 (librz/main/rz-hash.c:394) pending.
(gdb) r /bin/ls
Starting program: /usr/local/bin/rz-hash /bin/ls
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.32-4.fc33.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, rz_hash_parse_cmdline (ctx=0x7fffffffd450, argv=0x7fffffffd608, argc=<optimized out>) at ../librz/main/rz-hash.c:394
394		if (strstr(ctx->algorithm, "luhn")) {
(gdb) p ctx
$1 = (RzHashContext *) 0x7fffffffd450
(gdb) p ctx->algorithm
$2 = 0x0
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e62881 in __strstr_sse2_unaligned () from /lib64/libc.so.6
(gdb) 
```

**Comment by wargio** [comment]
oh. seems i forgot to check for the null ptr before running strstr
