### ISSUE TITLE
NULL pointer dereference in rz_analysis_block_recurse_depth_first

### ISSUE THREAD

**Issue by borzacchiello** [rizinorg/rizin#2065]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 44f8e8903d66a0d465908292bd4afb5de490ea03, build: 2021-12-04__09:51:27

### Actual behavior

If I _handcraft_ a new function with `af+` (without adding any basic block), and I execute the command `aa`, rizin crashes.

### Steps to reproduce the behavior

```
$ rizin /bin/ls
> af+ 0 a
> aa
[1]    7741 segmentation fault (core dumped)
```

stacktrace:
```
#0  rz_analysis_block_recurse_depth_first (block=0x0, cb=cb@entry=0x7ffff68ac700 <analysis_block_cb>, on_exit=on_exit@entry=0x7ffff68a8c80 <analysis_block_on_exit>, user=user@entry=0x7fffffffd550) at ../librz/analysis/block.c:500
#1  0x00007ffff68afd30 in rz_core_recover_vars (argonly=<optimized out>, fcn=0x5555556e96e0, core=<optimized out>) at ../librz/core/canalysis.c:3722
#2  rz_core_recover_vars (core=<optimized out>, fcn=0x5555556e96e0, argonly=<optimized out>) at ../librz/core/canalysis.c:3711
#3  0x00007ffff68b7500 in rz_core_analysis_all (core=core@entry=0x7ffff665a010) at ../librz/core/canalysis.c:4450
#4  0x00007ffff697f6d6 in cmd_analysis_all (input=0x5555556beea2 "", core=0x7ffff665a010) at ../librz/core/cmd/cmd_analysis.c:7421
#5  rz_cmd_analysis (data=0x7ffff665a010, input=0x5555556beea1 "a") at ../librz/core/cmd/cmd_analysis.c:8384
#6  0x00007ffff699be40 in call_cd (args=<optimized out>, cd=0x5555555b2400, cmd=<optimized out>) at ../librz/core/cmd/cmd_api.c:753
#7  rz_cmd_call_parsed_args (cmd=0x5555555a9e70, args=args@entry=0x5555556bee30) at ../librz/core/cmd/cmd_api.c:768
#8  0x00007ffff6991a2d in handle_ts_arged_stmt_internal (node_string=0x5555556bedf0 "aa", node=..., state=0x7fffffffda50) at ../librz/core/cmd/cmd.c:3981
#9  handle_ts_arged_stmt (state=0x7fffffffda50, node=...) at ../librz/core/cmd/cmd.c:3929
#10 0x00007ffff6929069 in handle_ts_stmt (state=state@entry=0x7fffffffda50, node=...) at ../librz/core/cmd/cmd.c:5429
#11 0x00007ffff696e3e2 in handle_ts_statements_internal (node_string=0x5555556bedd0 "aa", node=..., state=0x7fffffffda50) at ../librz/core/cmd/cmd.c:5486
#12 handle_ts_statements (state=state@entry=0x7fffffffda50, node=...) at ../librz/core/cmd/cmd.c:5451
#13 0x00007ffff696e803 in core_cmd_tsrzcmd (core=0x7fffffffda68, cstr=<optimized out>, split_lines=split_lines@entry=0x0, log=log@entry=0x1) at ../librz/core/cmd/cmd.c:5594
#14 0x00007ffff69623de in rz_core_cmd (core=core@entry=0x7ffff665a010, cstr=0x5555556e87d0 "aa", log=log@entry=0x1) at ../librz/core/cmd/cmd.c:5643
#15 0x00007ffff68eb4db in rz_core_prompt_exec (r=r@entry=0x7ffff665a010) at ../librz/core/core.c:2830
#16 0x00007ffff68ebb9e in rz_core_prompt_loop (r=r@entry=0x7ffff665a010) at ../librz/core/core.c:2681
#17 0x00007ffff7ea5723 in rz_main_rizin (argc=<optimized out>, argv=<optimized out>) at ../librz/main/rizin.c:1405
#18 0x00007ffff7cc7b25 in __libc_start_main () from /usr/lib/libc.so.6
#19 0x000055555555549e in _start ()
```

**Comment by ret2libc** [comment]
I believe this should be easy to fix.
