### ISSUE TITLE
Failure to detect `main` function in GraalVM-compiled Java ELF

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2072]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 35 x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64 (Java AOT)
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64
commit: d73920c90108cdf24e84b0807577c7e5342b7deb, build: 2021-12-06__11:54:26

### Expected behavior

`main()` function found at `0x424250`

### Actual behavior

`main()` function found at `0x824250`

```
[0x00405200]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[../librz/analysis/var.c:633:20: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x00405200]> s main
[0x00824250]> pi 4
add byte fs:[rcx], dh
add eax, dword [rdx]
retf 0x44
invalid
[0x00824250]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00824250  6400 3103 02ca 4400 2703                 d.1...D.'.
[0x00824250]> 
```

Note also the UBSAN report:
```
[../librz/analysis/var.c:633:20: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
```

### Steps to reproduce the behavior
- `rizin example`
- `aaa`
- `s main`

### Additional Logs, screenshots, source code,  configuration dump, ...

[graalvm-example.zip](https://github.com/rizinorg/rizin/files/7659605/graalvm-example.zip)

IDA Pro 7.6 output:
```
.text:0000000000424250 ; =============== S U B R O U T I N E =======================================
.text:0000000000424250
.text:0000000000424250
.text:0000000000424250 ; int __cdecl main(int argc, const char **argv, const char **envp)
.text:0000000000424250                 public main
.text:0000000000424250 main            proc near               ; DATA XREF: LOAD:00000000004011A0↑o
.text:0000000000424250                                         ; LOAD:00000000004011D0↑o ...
.text:0000000000424250
.text:0000000000424250 var_68          = dword ptr -68h
.text:0000000000424250 var_60          = qword ptr -60h
.text:0000000000424250 var_58          = qword ptr -58h
.text:0000000000424250 var_50          = qword ptr -50h
.text:0000000000424250 var_48          = qword ptr -48h
.text:0000000000424250 var_40          = qword ptr -40h
.text:0000000000424250 var_38          = qword ptr -38h
.text:0000000000424250 var_30          = qword ptr -30h
.text:0000000000424250 var_28          = qword ptr -28h
.text:0000000000424250 var_20          = qword ptr -20h
.text:0000000000424250 var_18          = qword ptr -18h
.text:0000000000424250 var_10          = qword ptr -10h
.text:0000000000424250 var_4           = dword ptr -4
.text:0000000000424250
.text:0000000000424250                 sub     rsp, 68h        ; Alternative name is 'IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e'
.text:0000000000424254                 mov     rax, r14
.text:0000000000424257                 mov     rcx, r15
.text:000000000042425A                 lea     rdx, unk_E4E570
.text:0000000000424261                 mov     dword ptr [rdx], 3
.text:0000000000424267                 mov     [rdx+20h], edi
.text:000000000042426A                 mov     [rdx+28h], rsi
.text:000000000042426E                 mov     r15, 0
.text:0000000000424275                 mov     [rsp+68h+var_4], edi
.text:0000000000424279                 mov     rdi, rdx
.text:000000000042427C                 mov     [rsp+68h+var_10], rsi
.text:0000000000424281                 mov     esi, 0F0h
.text:0000000000424286                 mov     [rsp+68h+var_18], rcx
.text:000000000042428B                 mov     [rsp+68h+var_20], rax
.text:0000000000424290                 mov     [rsp+68h+var_28], r13
.text:0000000000424295                 mov     [rsp+68h+var_30], r12
.text:000000000042429A                 mov     [rsp+68h+var_38], rbp
.text:000000000042429F                 mov     [rsp+68h+var_40], rbx
.text:00000000004242A4                 mov     [rsp+68h+var_48], rdx
.text:00000000004242A9                 call    sub_443780
.text:00000000004242AE                 nop
.text:00000000004242AF                 test    eax, eax
.text:00000000004242B1                 jz      loc_424393
.text:00000000004242B7
.text:00000000004242B7 loc_4242B7:                             ; CODE XREF: main+173↓j
.text:00000000004242B7                 test    eax, eax
.text:00000000004242B9                 jnz     loc_424461
.text:00000000004242BF                 mov     rdi, offset loc_59D4E8
.text:00000000004242C9                 lea     rdi, [r14+rdi]
.text:00000000004242CD                 mov     rsi, offset loc_54E620
.text:00000000004242D7                 lea     rsi, [r14+rsi]
.text:00000000004242DB                 call    sub_4143C0
.text:00000000004242E0                 nop
.text:00000000004242E1                 mov     rax, 1FAD90h
.text:00000000004242EB                 lea     rax, [r14+rax]
.text:00000000004242EF                 mov     rcx, 576AC8h
.text:00000000004242F9                 lea     rcx, [r14+rcx]
.text:00000000004242FD                 mov     rdi, 576AE8h
.text:0000000000424307                 lea     rdi, [r14+rdi]
.text:000000000042430B                 mov     [rsp+68h+var_50], rax
.text:0000000000424310                 mov     [rsp+68h+var_58], rcx
.text:0000000000424315                 call    sub_44F4A0
.text:000000000042431A                 nop
```
Ghirda output:
```
                         *******************************************************
                         *                      FUNCTION                       *
                         *******************************************************
                         undefined IsolateEnterStub__JavaMainWrapper__run_
           undefined       AL:1         <RETURN>
           undefined4      Stack[-0x4]  local_4                            XREF[1]:   00424275(W)  
           undefined8      Stack[-0x10  local_10                           XREF[1]:   0042427c(W)  
           undefined8      Stack[-0x18  local_18                           XREF[4]:   00424286(W), 
                                                                                      00424389(R), 
                                                                                      004243fc(R), 
                                                                                      00424489(R)  
           undefined8      Stack[-0x20  local_20                           XREF[4]:   0042428b(W), 
                                                                                      00424384(R), 
                                                                                      004243f7(R), 
                                                                                      00424484(R)  
           undefined8      Stack[-0x28  local_28                           XREF[4]:   00424290(W), 
                                                                                      0042437f(R), 
                                                                                      004243f2(R), 
                                                                                      0042447f(R)  
           undefined8      Stack[-0x30  local_30                           XREF[4]:   00424295(W), 
                                                                                      0042437a(R), 
                                                                                      004243ed(R), 
                                                                                      0042447a(R)  
           undefined8      Stack[-0x38  local_38                           XREF[4]:   0042429a(W), 
                                                                                      00424375(R), 
                                                                                      004243e8(R), 
                                                                                      00424475(R)  
           undefined8      Stack[-0x40  local_40                           XREF[4]:   0042429f(W), 
                                                                                      00424370(R), 
                                                                                      004243e3(R), 
                                                                                      00424470(R)  
           undefined8      Stack[-0x48  local_48                           XREF[2]:   004242a4(W), 
                                                                                      004243b8(R)  
           undefined8      Stack[-0x50  local_50                           XREF[8]:   0042430b(W), 
                                                                                      00424342(R), 
                                                                                      00424353(R), 
                                                                                      004243d8(W), 
                                                                                      0042441d(R), 
                                                                                      0042442e(R), 
                                                                                      004244a1(R), 
                                                                                      004244b2(R)  
           undefined8      Stack[-0x58  local_58                           XREF[6]:   00424310(W), 
                                                                                      00424337(R), 
                                                                                      00424412(R), 
                                                                                      0042448e(R), 
                                                                                      00424493(W), 
                                                                                      004244bd(R)  
           undefined4      Stack[-0x68  local_68                           XREF[1]:   0042436c(*)  
                         main                                      XREF[2]:   Entry Point(*), 
                         IsolateEnterStub__JavaMainWrapper__run__              entry:00405218(*)  
      00424250 48 83 ec      SUB       RSP,0x68
               68
      00424254 49 8b c6      MOV       RAX,R14
      00424257 49 8b cf      MOV       RCX,R15
      0042425a 48 8d 15      LEA       RDX,[DAT_00e4e570]
               0f a3 a2 
               00
      00424261 c7 02 03      MOV       dword ptr [RDX]=>DAT_00e4e570,0x3
               00 00 00
      00424267 89 7a 20      MOV       dword ptr [RDX + 0x20]=>DAT_00e4e590,EDI
      0042426a 48 89 72      MOV       qword ptr [RDX + 0x28]=>DAT_00e4e598,RSI
               28
      0042426e 49 c7 c7      MOV       R15,0x0
               00 00 00 
               00
      00424275 89 7c 24      MOV       dword ptr [RSP + local_4],EDI
               64
      00424279 48 8b fa      MOV       RDI=>DAT_00e4e570,RDX
      0042427c 48 89 74      MOV       qword ptr [RSP + local_10],RSI
               24 58
      00424281 be f0 00      MOV       ESI,0xf0
               00 00
      00424286 48 89 4c      MOV       qword ptr [RSP + local_18],RCX
               24 50
      0042428b 48 89 44      MOV       qword ptr [RSP + local_20],RAX
               24 48
      00424290 4c 89 6c      MOV       qword ptr [RSP + local_28],R13
               24 40
      00424295 4c 89 64      MOV       qword ptr [RSP + local_30],R12
               24 38
      0042429a 48 89 6c      MOV       qword ptr [RSP + local_38],RBP
               24 30
      0042429f 48 89 5c      MOV       qword ptr [RSP + local_40],RBX
               24 28
      004242a4 48 89 54      MOV       qword ptr [RSP + local_48],RDX=>DAT_00e4e
               24 20
      004242a9 e8 d2 f4      CALL      FUN_00443780                               undefined FUN_00443780()
               01 00
      004242ae 90            NOP
      004242af 85 c0         TEST      EAX,EAX
      004242b1 0f 84 dc      JZ        LAB_00424393
               00 00 00
                         LAB_004242b7                              XREF[1]:   004243c3(j)  
      004242b7 85 c0         TEST      EAX,EAX
      004242b9 0f 85 a2      JNZ       LAB_00424461
               01 00 00
      004242bf 48 bf e8      MOV       RDI,0x59d4e8
               d4 59 00 
               00 00 00
      004242c9 49 8d 3c      LEA       RDI,[R14 + RDI*0x1]
               3e
      004242cd 48 be 20      MOV       RSI,0x54e620
               e6 54 00 
               00 00 00
      004242d7 49 8d 34      LEA       RSI,[R14 + RSI*0x1]
               36
      004242db e8 e0 00      CALL      FUN_004143c0                               undefined FUN_004143c0()
               ff ff
      004242e0 90            NOP
      004242e1 48 b8 90      MOV       RAX,0x1fad90
               ad 1f 00 
               00 00 00
```

**Comment by chinggg** [comment]
Rizin can detect function at `0x424250` but name it as `sym.main`. The address of symbol flag `main` seems to be wrong.
```cmd
[0x00405200]> aaa
[0x00405200]> afl | grep main
0x00424250    9 499          sym.main
[0x00405200]> fl | grep main
0x00000000 16 sym.imp.__libc_start_main
0x00424250 499 sym.main
0x00824250 256 main
0x00e4cfd8 8 reloc.__libc_start_main
0x00e4e500 35 str.Failed_to_create_the_main_Isolate.
[0x00405200]> s main
[0x00824250]>
```

Radare2 seems to be right
```cmd
[0x00405200]> aaa
[0x00405200]> afl | grep main
0x00424250   10 631  -> 601  main
[0x00405200]> f | grep main
0x00000000 16 sym.imp.__libc_start_main
0x00424250 631 main
0x00424250 693 sym.main
0x00e4cfd8 8 reloc.__libc_start_main
0x00e4e500 35 str.Failed_to_create_the_main_Isolate.
[0x00405200]> s main
[0x00424250]>
```

Using gdb to debug rizin, we can see that in `num_callback()`,  `rz_analysis_get_function_byname("main")` does not return valid result so it use the result of `rz_flag_get("main")`, which is `0x824250`
```cmd
[0x00405200]> s main

Breakpoint 1, num_callback (userptr=0x7ffff669a010, str=0x55555555e488 "main", ok=0x7fffffffdb38) at ../librz/core/core.c:409
409     static ut64 num_callback(RzNum *userptr, const char *str, int *ok) {
(gdb) bt
#0  num_callback (userptr=0x7ffff669a010, str=0x55555555e488 "main", ok=0x7fffffffdb38) at ../librz/core/core.c:409
#1  0x00007ffff7f49ca3 in rz_num_get (num=num@entry=0x55555555e440, str=str@entry=0x55555555e488 "main") at ../librz/util/unum.c:194
#2  0x00007ffff7f1c157 in prim (num=num@entry=0x55555555e440, nc=nc@entry=0x55555555e470, get=get@entry=0) at ../librz/util/calc.c:230
#3  0x00007ffff7f1c2a7 in term (num=num@entry=0x55555555e440, nc=nc@entry=0x55555555e470, get=get@entry=0) at ../librz/util/calc.c:190
#4  0x00007ffff7f1c55c in expr (num=num@entry=0x55555555e440, nc=nc@entry=0x55555555e470, get=get@entry=0) at ../librz/util/calc.c:168
#5  0x00007ffff7f1c8c3 in rz_num_calc (num=num@entry=0x55555555e440, str=str@entry=0x55555e2fd760 "main", err=err@entry=0x7fffffffe0e0) at ../librz/util/calc.c:507
#6  0x00007ffff7f4a70c in rz_num_math (num=0x55555555e440, str=str@entry=0x55555e2fd760 "main") at ../librz/util/unum.c:457
#7  0x00007ffff6986852 in rz_seek_handler (core=0x7ffff669a010, argc=<optimized out>, argv=0x55555efabfb0) at ../librz/core/cmd/cmd_seek.c:175

(gdb) p/s str
$1 = 0x55555555e488 "main"

(gdb) n
418             if (ok) {
(gdb) n
419                     *ok = false;
(gdb) n
421             switch (*str) {
(gdb) n
717                     if (*str >= 'A') {
(gdb) n
719                             RzAnalysisFunction *fcn = rz_analysis_get_function_byname(core->analysis, str);
(gdb) n
720                             if (fcn) {
(gdb) p fcn
$2 = (RzAnalysisFunction *) 0x0
(gdb) n
734                             if ((flag = rz_flag_get(core->flags, str))) {
(gdb) n
735                                     ret = flag->offset;
(gdb) p/x flag->offset
$3 = 0x824250
```

To solve this problem:
1. Why function at `0x424250` is named as `sym.main`? Should the functon be named as `main` in the first place, or `sym.main` then let `rz_analysis_get_function_byname("main")` successfully return address of `sym.main`.
2. Why the address symbol flag `main` is `0x824250`, which is `0x400000` larger than the correct address?

**Update 1** for where the `main` flag is set in rizin:
```cmd
Breakpoint 1, rz_core_bin_apply_main (r=r@entry=0x7ffff669a010, binfile=binfile@entry=0x555555693c90, va=va@entry=true) at ../librz/core/cbin.c:639
639             rz_return_val_if_fail(r && binfile, false);
(gdb) n
644             const RzBinAddr *binmain = rz_bin_object_get_special_symbol(o, RZ_BIN_SPECIAL_SYMBOL_MAIN);
(gdb) p/x binmain->paddr
$4 = 0x424250
(gdb) p/x binmain->vaddr
$5 = 0x824250
648             ut64 addr = va ? rz_bin_object_addr_with_base(o, binmain->vaddr) : binmain->paddr;
(gdb) p/x addr
$6 = 0x824250
(gdb) n
650             rz_flag_set(r->flags, "main", addr, r->blocksize);
```

r2 counterpart:
```cmd
Breakpoint 1, bin_main (r=0x7ffff5454010, pj=0x0, mode=2, va=1) at cbin.c:1324
1324            RBinAddr *binmain = r_bin_get_sym (r->bin, R_BIN_SYM_MAIN);
(gdb) p/x binmain->paddr
$3 = 0x24250
(gdb) p/x binmain->vaddr
$4 = 0x424250
(gdb) n
1333            addr = va ? r_bin_a2b (r->bin, binmain->vaddr) : binmain->paddr;
(gdb) p/x addr
$5 = 0x424250
```

**Update 2** for where `SPECIAL_SYMBOL_MAIN` of RzBinObject (`o->binsym[i]`) is set from `binsym()` of elf plugin `( p->binsym(bf, i))` in rizin:
```cmd
Breakpoint 1, rz_bin_object_set_items (bf=bf@entry=0x555555693c90, o=o@entry=0x555555693780) at ../librz/bin/bobj.c:377

405                     for (i = 0; i < RZ_BIN_SPECIAL_SYMBOL_LAST; i++) {
(gdb) n
406                             o->binsym[i] = p->binsym(bf, i);
(gdb) p i
$10 = 2
(gdb) n
407                             if (o->binsym[i]) {
(gdb) p/x o->binsym[i]->paddr
$11 = 0x424250
(gdb) p/x o->binsym[i]->vaddr
$12 = 0x824250
```

r2 counterpart:
```cmd
Breakpoint 1, r_bin_object_set_items (bf=0x5555556af760, o=0x5555556b0510) at bobj.c:266

298                     for (i = 0; i < R_BIN_SYM_LAST; i++) {
(gdb) n
299                             o->binsym[i] = p->binsym (bf, i);
(gdb) p i
$3 = 2
(gdb) n
300                             if (o->binsym[i]) {
(gdb) p/x o->binsym[i]->paddr
$5 = 0x24250
(gdb) p/x o->binsym[i]->vaddr
$6 = 0x424250
```

**Update 3** 
In rizin, the main offset is calculated as below, setting paddr=0x424250:
```cmd
(gdb) bt
#0  rz_read_le32 (src=<optimized out>) at ../librz/bin/format/elf/elf_info.c:318
#1  get_main_offset_linux_64_pie (buf=0x7fffffffe1a0 "\363\017\036\372\061\355I\211\321^H\211\342H\203\344\360PTE1\300\061\311H\307\307PBB", entry=20992, bin=0x5555556c7db0)
    at ../librz/bin/format/elf/elf_info.c:320
#2  Elf64_rz_bin_elf_get_main_offset (bin=0x5555556c7db0) at ../librz/bin/format/elf/elf_info.c:1922
#3  0x00007ffff6b4e0ae in binsym_aux (sym=<optimized out>, bin=0x5555556c7db0) at ../librz/bin/p/bin_elf.inc:111
#4  binsym (bf=<optimized out>, sym=<optimized out>) at ../librz/bin/p/bin_elf.inc:155
#5  0x00007ffff6b3f0a4 in rz_bin_object_set_items (bf=bf@entry=0x555555693c90, o=o@entry=0x555555693780) at ../librz/bin/bobj.c:406
```
 It should be noticed that #1880 add check for Fedora binary, so it correctly changes the begin offset to 24:
```diff
if (buf[0] == 0xf3 && buf[1] == 0x0f && buf[2] == 0x1e && buf[3] == 0xfa) {
    // Change begin offset if binary starts with 'endbr64'
    bo = 33;
+    // double xor for init and fini
+    if (!memcmp(buf + 19, "\x45\x31\xc0\x31\xc9", 5)) {
+	bo = 24;
+    }
}
```
r2 fails here, but it has `getmainsymbol` as a last resort to find `sym.main` if possible, which called `Elf_(r_bin_elf_get_symbols)`.

**Comment by kazarmy** [comment]
> 2. Why the address symbol flag `main` is `0x824250`, which is `0x400000` larger than the correct address?

`get_main_offset_linux_64_pie()` returns the correct address (`0x424250`) and `0x400000` happens to be the virtual address of the first LOAD segment (which I suspect is involved somehow). I don't have much time to work on this, so if you can solve this mystery, that would be great!

**Comment by kazarmy** [comment]
> r2 fails at here, but it has `getmainsymbol` to find `sym.main` if possible

The problem with `sym.main` as you alluded here (apart from the possibility of it actually containing an incorrect address) is that it might not even exist.

**Comment by chinggg** [comment]
> The problem with sym.main as you alluded here (apart from the possibility of it actually containing an incorrect address) is that it might not even exist.

You mean this binary does not even have symbol `main`? But I can see the symbol `main` using some tools (except `objdump -t` because this binary has only `.dynsym`)

```shell
❯ nm -D example
0000000000424250 T main
❯ readelf -s example | grep main
Symbol table '.dynsym' contains 153 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
   131: 0000000000424250   693 FUNC    GLOBAL DEFAULT   14 main
❯ rz-bin -s example
[Symbols]
nth paddr      vaddr      bind   type   size lib name
131 0x00024250 0x00424250 GLOBAL FUNC   693      main
```

What confuses me is why `rz-bin` has the output of `paddr=0x24250` but `p->binsym(bf, 2)` returns `0x424250`

**Comment by kazarmy** [comment]
This binary does not have symbol `main`: https://github.com/rizinorg/rizin-testbins/blob/master/elf/analysis/fedora_35_x86_64bit_ls and it cannot be assumed that future binaries will have that symbol.

> What confuses me is why `rz-bin` has the output of `paddr=0x24250` but `p->binsym(bf, 2)` returns `0x424250`

This probably suggests the cause of this issue but the code still needs to be fixed.

**Comment by chinggg** [comment]
I have debug and see the value returned by `rz_read_le32` is `0x424250`, but it should be `0x24250` since it is paddr, is there anything special about the condition `bo=24`? May be the value should not be returned directly?
```c
static ut64 get_main_offset_linux_64_pie(ELFOBJ *bin, ut64 entry, ut8 *buf) {
	/* linux64 pie main -- probably buggy in some cases */
	int bo = 29; // Begin offset may vary depending on the entry prelude
	// endbr64 - fedora bins have this
	if (buf[0] == 0xf3 && buf[1] == 0x0f && buf[2] == 0x1e && buf[3] == 0xfa) {
		// Change begin offset if binary starts with 'endbr64'
		bo = 33;
		// double xor for init and fini
		if (!memcmp(buf + 19, "\x45\x31\xc0\x31\xc9", 5)) {
			bo = 24;
		}
	}
	if (buf[bo] == 0x48) {
		ut8 ch = buf[bo + 1];
		if (ch == 0x8d) { // lea rdi, qword [rip-0x21c4]
                   
		} else if (0xc7) { // mov rdi, 0xADDR
			ut8 *p = buf + bo + 3;
			return (ut64)(ut32)rz_read_le32(p);
		}
	}

	return UT64_MAX;
}

**Comment by kazarmy** [comment]
> ... is there anything special about the condition bo=24?

It should be the offset for the `mov rdi`.

> May be the value should not be returned directly?

Maybe.
