### ISSUE TITLE
Multiple heap-based OOB reads when disassemblying opcodes

### ISSUE THREAD

**Issue by OctavioGalland** [rizinorg/rizin#2082]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04 amd64
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | QUALCOMM DSP6, Propeller
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 5b6aaed68d84ac13de49b9400bd3bc7fe44eacbc, build: 2021-12-09__11:19:29

### Expected behavior

Analyzing binaries shouldn't trigger OOB memory accesses.

### Actual behavior

There is a heap-based out of bounds read in `rz_read_be32` and `rz_read_le32` when reversing QUALCOMM DSP6 and Propeller binaries, respectively.

### Steps to reproduce the behavior
Analyze the binaries attached below with `aaa` on an asan build to reproduce the crashes (the qualcomm based binary is the one called `id:000154,sig:06,sync:f1,src:055226` and the other one is the propeller one).
[binaries.zip](https://github.com/rizinorg/rizin/files/7686294/binaries.zip)

### Additional Logs, screenshots, source code,  configuration dump, ...
```
$ LD_LIBRARY_PATH=/home/faraday/rizin_dyn_asan/lib/x86_64-linux-gnu/ /home/faraday/rizin_dyn_asan/bin/rizin -TQA crashes/id:000140,sig:06,sync:f2,src:050325
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[=================================================================
==61099==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500000c0a0 at pc 0x7fbfca3249ac bp 0x7ffee490a920 sp 0x7ffee490a910
READ of size 1 at 0x62500000c0a0 thread T0
    #0 0x7fbfca3249ab in rz_read_be32 ../librz/include/rz_endian.h:87
    #1 0x7fbfca3250bf in propeller_decode_command ../librz/asm/arch/propeller/propeller_disas.c:210
    #2 0x7fbfca291fc5 in propeller_op ../librz/analysis/p/analysis_propeller.c:20
    #3 0x7fbfca196921 in rz_analysis_op ../librz/analysis/op.c:117
    #4 0x7fbfc921d90c in rz_core_analysis_search_xrefs ../librz/core/canalysis.c:4281
    #5 0x7fbfc93fe448 in rz_core_analysis_refs ../librz/core/cmd/cmd_analysis.c:6615
    #6 0x7fbfc9231070 in rz_core_analysis_everything ../librz/core/canalysis.c:6681
    #7 0x7fbfc9400dad in cmd_analysis_all ../librz/core/cmd/cmd_analysis.c:6993
    #8 0x7fbfc9406ec7 in rz_cmd_analysis ../librz/core/cmd/cmd_analysis.c:7937
    #9 0x7fbfc94ceb81 in call_cd ../librz/core/cmd/cmd_api.c:755
    #10 0x7fbfc94cec3a in rz_cmd_call_parsed_args ../librz/core/cmd/cmd_api.c:770
    #11 0x7fbfc94b262a in handle_ts_arged_stmt_internal ../librz/core/cmd/cmd.c:3981
    #12 0x7fbfc94b1b13 in handle_ts_arged_stmt ../librz/core/cmd/cmd.c:3929
    #13 0x7fbfc94c56d4 in handle_ts_stmt ../librz/core/cmd/cmd.c:5430
    #14 0x7fbfc94c6180 in handle_ts_statements_internal ../librz/core/cmd/cmd.c:5487
    #15 0x7fbfc94c5a5d in handle_ts_statements ../librz/core/cmd/cmd.c:5452
    #16 0x7fbfc94c6dd9 in core_cmd_tsrzcmd ../librz/core/cmd/cmd.c:5595
    #17 0x7fbfc94c7342 in rz_core_cmd ../librz/core/cmd/cmd.c:5644
    #18 0x7fbfc94c84b0 in rz_core_cmd0 ../librz/core/cmd/cmd.c:5865
    #19 0x7fbfccab5f13 in rz_main_rizin ../librz/main/rizin.c:1355
    #20 0x556342a099bd in main ../binrz/rizin/rizin.c:57
    #21 0x7fbfcc8be0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #22 0x556342a092ed in _start (/home/faraday/rizin_dyn_asan/bin/rizin+0x22ed)

0x62500000c0a0 is located 0 bytes to the right of 8096-byte region [0x62500000a100,0x62500000c0a0)
allocated by thread T0 here:
    #0 0x7fbfccf26bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fbfc921d5cc in rz_core_analysis_search_xrefs ../librz/core/canalysis.c:4248
    #2 0x7fbfc93fe448 in rz_core_analysis_refs ../librz/core/cmd/cmd_analysis.c:6615
    #3 0x7fbfc9231070 in rz_core_analysis_everything ../librz/core/canalysis.c:6681
    #4 0x7fbfc9400dad in cmd_analysis_all ../librz/core/cmd/cmd_analysis.c:6993
    #5 0x7fbfc9406ec7 in rz_cmd_analysis ../librz/core/cmd/cmd_analysis.c:7937
    #6 0x7fbfc94ceb81 in call_cd ../librz/core/cmd/cmd_api.c:755
    #7 0x7fbfc94cec3a in rz_cmd_call_parsed_args ../librz/core/cmd/cmd_api.c:770
    #8 0x7fbfc94b262a in handle_ts_arged_stmt_internal ../librz/core/cmd/cmd.c:3981
    #9 0x7fbfc94b1b13 in handle_ts_arged_stmt ../librz/core/cmd/cmd.c:3929
    #10 0x7fbfc94c56d4 in handle_ts_stmt ../librz/core/cmd/cmd.c:5430
    #11 0x7fbfc94c6180 in handle_ts_statements_internal ../librz/core/cmd/cmd.c:5487
    #12 0x7fbfc94c5a5d in handle_ts_statements ../librz/core/cmd/cmd.c:5452
    #13 0x7fbfc94c6dd9 in core_cmd_tsrzcmd ../librz/core/cmd/cmd.c:5595
    #14 0x7fbfc94c7342 in rz_core_cmd ../librz/core/cmd/cmd.c:5644
    #15 0x7fbfc94c84b0 in rz_core_cmd0 ../librz/core/cmd/cmd.c:5865
    #16 0x7fbfccab5f13 in rz_main_rizin ../librz/main/rizin.c:1355
    #17 0x556342a099bd in main ../binrz/rizin/rizin.c:57
    #18 0x7fbfcc8be0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../librz/include/rz_endian.h:87 in rz_read_be32
Shadow bytes around the buggy address:
  0x0c4a7fff97c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff97d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff97e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff97f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff9800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4a7fff9810: 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9820: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9830: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9840: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9850: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9860: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==61099==ABORTING
```

```
$ LD_LIBRARY_PATH=/home/faraday/rizin_dyn_asan/lib/x86_64-linux-gnu/ /home/faraday/rizin_dyn_asan/bin/rizin -TQA crashes/id:000154,sig:06,sync:f1,src:055226
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[=================================================================
==61129==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6250000098a1 at pc 0x7fbd3ddb7f56 bp 0x7ffce1680750 sp 0x7ffce1680740
READ of size 1 at 0x6250000098a1 thread T0
    #0 0x7fbd3ddb7f55 in rz_read_le32 ../librz/include/rz_endian.h:242
    #1 0x7fbd3ddbb1e2 in hexagon_reverse_opcode ../librz/asm/arch/hexagon/hexagon_arch.c:674
    #2 0x7fbd3d153c36 in hexagon_v6_op ../librz/analysis/p/analysis_hexagon.c:25
    #3 0x7fbd3d088921 in rz_analysis_op ../librz/analysis/op.c:117
    #4 0x7fbd3c10f90c in rz_core_analysis_search_xrefs ../librz/core/canalysis.c:4281
    #5 0x7fbd3c2f0448 in rz_core_analysis_refs ../librz/core/cmd/cmd_analysis.c:6615
    #6 0x7fbd3c123070 in rz_core_analysis_everything ../librz/core/canalysis.c:6681
    #7 0x7fbd3c2f2dad in cmd_analysis_all ../librz/core/cmd/cmd_analysis.c:6993
    #8 0x7fbd3c2f8ec7 in rz_cmd_analysis ../librz/core/cmd/cmd_analysis.c:7937
    #9 0x7fbd3c3c0b81 in call_cd ../librz/core/cmd/cmd_api.c:755
    #10 0x7fbd3c3c0c3a in rz_cmd_call_parsed_args ../librz/core/cmd/cmd_api.c:770
    #11 0x7fbd3c3a462a in handle_ts_arged_stmt_internal ../librz/core/cmd/cmd.c:3981
    #12 0x7fbd3c3a3b13 in handle_ts_arged_stmt ../librz/core/cmd/cmd.c:3929
    #13 0x7fbd3c3b76d4 in handle_ts_stmt ../librz/core/cmd/cmd.c:5430
    #14 0x7fbd3c3b8180 in handle_ts_statements_internal ../librz/core/cmd/cmd.c:5487
    #15 0x7fbd3c3b7a5d in handle_ts_statements ../librz/core/cmd/cmd.c:5452
    #16 0x7fbd3c3b8dd9 in core_cmd_tsrzcmd ../librz/core/cmd/cmd.c:5595
    #17 0x7fbd3c3b9342 in rz_core_cmd ../librz/core/cmd/cmd.c:5644
    #18 0x7fbd3c3ba4b0 in rz_core_cmd0 ../librz/core/cmd/cmd.c:5865
    #19 0x7fbd3f9a7f13 in rz_main_rizin ../librz/main/rizin.c:1355
    #20 0x55a1c77279bd in main ../binrz/rizin/rizin.c:57
    #21 0x7fbd3f7b00b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #22 0x55a1c77272ed in _start (/home/faraday/rizin_dyn_asan/bin/rizin+0x22ed)

0x6250000098a1 is located 1 bytes to the right of 8096-byte region [0x625000007900,0x6250000098a0)
allocated by thread T0 here:
    #0 0x7fbd3fe18bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fbd3c10f5cc in rz_core_analysis_search_xrefs ../librz/core/canalysis.c:4248
    #2 0x7fbd3c2f0448 in rz_core_analysis_refs ../librz/core/cmd/cmd_analysis.c:6615
    #3 0x7fbd3c123070 in rz_core_analysis_everything ../librz/core/canalysis.c:6681
    #4 0x7fbd3c2f2dad in cmd_analysis_all ../librz/core/cmd/cmd_analysis.c:6993
    #5 0x7fbd3c2f8ec7 in rz_cmd_analysis ../librz/core/cmd/cmd_analysis.c:7937
    #6 0x7fbd3c3c0b81 in call_cd ../librz/core/cmd/cmd_api.c:755
    #7 0x7fbd3c3c0c3a in rz_cmd_call_parsed_args ../librz/core/cmd/cmd_api.c:770
    #8 0x7fbd3c3a462a in handle_ts_arged_stmt_internal ../librz/core/cmd/cmd.c:3981
    #9 0x7fbd3c3a3b13 in handle_ts_arged_stmt ../librz/core/cmd/cmd.c:3929
    #10 0x7fbd3c3b76d4 in handle_ts_stmt ../librz/core/cmd/cmd.c:5430
    #11 0x7fbd3c3b8180 in handle_ts_statements_internal ../librz/core/cmd/cmd.c:5487
    #12 0x7fbd3c3b7a5d in handle_ts_statements ../librz/core/cmd/cmd.c:5452
    #13 0x7fbd3c3b8dd9 in core_cmd_tsrzcmd ../librz/core/cmd/cmd.c:5595
    #14 0x7fbd3c3b9342 in rz_core_cmd ../librz/core/cmd/cmd.c:5644
    #15 0x7fbd3c3ba4b0 in rz_core_cmd0 ../librz/core/cmd/cmd.c:5865
    #16 0x7fbd3f9a7f13 in rz_main_rizin ../librz/main/rizin.c:1355
    #17 0x55a1c77279bd in main ../binrz/rizin/rizin.c:57
    #18 0x7fbd3f7b00b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../librz/include/rz_endian.h:242 in rz_read_le32
Shadow bytes around the buggy address:
  0x0c4a7fff92c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff92d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff92e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff92f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a7fff9300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4a7fff9310: 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9320: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9330: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9340: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9350: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a7fff9360: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==61129==ABORTING
```

**Comment by XVilka** [comment]
@Rot127 looks like it's Hexagon ELF-related issue, please take a look when you have time.
