### ISSUE TITLE
Segfault when running aaa against sample

### ISSUE THREAD

**Issue by re-fox** [rizinorg/rizin#2173]
### Work environment
 - Fedora 35

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Fedora 35 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| `rizin -v` full output, **not truncated** (mandatory)  | `rizin 0.4.0-git @ linux-x86-64 commit: 63a3fbde2db582665157ecbe878d953d2f64ca82, build: 2022-01-04__15:31:01`

### Expected behavior
- Analysis will complete

### Actual behavior
Rizin will crash when running `aaa` against this sample.  

### Steps to reproduce the behavior
Load the following sample in rizin [rizin_sample.zip](https://github.com/rizinorg/rizin/files/7808687/rizin_sample.zip) (password: infected)
The binary can be analyzed with `aa`, however running `aaa` will result in `Segmentation fault (core dumped)`
```
$ rizin rizin_sample
[0x00407a10]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)

[0x00407a10]> afl
0x00407a10   35 769          entry0
0x004018d0    3 30           sym.dmhelpserver.exe_DllCanUnloadNow
0x00408324    1 6            sub.kernel32.dll_GetProcAddress
0x00401890    3 50           sym.dmhelpserver.exe_DllGetClassObject
0x00401990   10 274          fcn.00401990
0x00401850    3 30           sym.dmhelpserver.exe_DllRegisterServer
0x00401870    3 30           sym.dmhelpserver.exe_DllUnregisterServer

0x00407a10]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[Cannot find base type ""s for all functions (aaft)
Cannot find base type ""
Cannot find base type ""
Cannot convert the type for the variable "fcn.0040dae4.arg_8h" into pointer
Cannot find base type "REFCLSID"
Cannot find base type "REFCLSID"
Cannot find base type ""
...snipped...
Cannot find base type ""
Cannot convert the type for the variable "fcn.004024e0.arg_8h" into pointer
Cannot find base type ""
...snipped....
Segmentation fault (core dumped)
```

**Comment by re-fox** [comment]
Updating with information from ASAN 
```
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[Cannot convert the type for the variable "fcn.0040dae4.arg_8h" into pointer
Cannot convert the type for the variable "fcn.004024e0.arg_8h" into pointer
../librz/core/analysis_tp.c:120:37: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'struct RzAnalysisVar', which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1023497==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fc7883f02fe bp 0x7fffc4c10530 sp 0x7fffc4c104f0 T0)
==1023497==The signal is caused by a READ memory access.
==1023497==Hint: address points to the zero page.
    #0 0x7fc7883f02fd in var_type_set.part.0 (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0xd672fd)
    #1 0x7fc7883f78be in propagate_types_among_used_variables (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0xd6e8be)
    #2 0x7fc7883fd4d8 in rz_core_analysis_type_match (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0xd744d8)
    #3 0x7fc78845fc83 in rz_core_analysis_types_propagation (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0xdd6c83)
    #4 0x7fc788463948 in rz_core_analysis_everything (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0xdda948)
    #5 0x7fc78888f052 in rz_cmd_analysis (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x1206052)
    #6 0x7fc7888eb24c in rz_cmd_call_parsed_args (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x126224c)
    #7 0x7fc788870d51 in handle_ts_arged_stmt (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x11e7d51)
    #8 0x7fc7886b45c5 in handle_ts_stmt (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x102b5c5)
    #9 0x7fc78882bdc4 in handle_ts_statements (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x11a2dc4)
    #10 0x7fc78882d16c in core_cmd_tsrzcmd (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x11a416c)
    #11 0x7fc7887dcc76 in rz_core_cmd (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0x1153c76)
    #12 0x7fc7953e00ce in rz_main_rizin (/usr/local/bin/../lib/x86_64-linux-gnu/librz_main.so.0.4.0-git+0x850ce)
    #13 0x7fc7948230b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #14 0x5617da21cadd in _start (/usr/local/bin/rizin+0x2add)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/bin/../lib/x86_64-linux-gnu/librz_core.so.0.4.0-git+0xd672fd) in var_type_set.part.0
==1023497==ABORTING
```

**Comment by ret2libc** [comment]
Thanks for your additional info. I will look at this in the next day!

**Comment by h4x5p4c3** [comment]
i did encounter a similar issue with my arch linux

**Comment by ret2libc** [comment]
This should be fixed now in `dev` branch. Please re-open if I'm wrong.
