### ISSUE TITLE
Two small memory leaks

### ISSUE THREAD

**Issue by ajakk** [rizinorg/rizin#2307]
Each of the attached files (when un-gzipped) produce memory leaks, one example:

```sh
$ ./binrz/rizin/rizin -Aq ~/Downloads/id\ 000009\,sig\ 06\,src\ 012103+009495\,time\ 506124955\,op\ splice\,rep\ 8
Undefined type in free_object (0)
Undefined type in get_object (0x7d)
Undefined type in get_object (0x0)
Undefined type in get_object (0x0)
Undefined type in get_object (0x1b)
Undefined type in get_object (0x0)
Undefined type in get_object (0x0)
Undefined type in get_object (0x1b)
Undefined type in get_object (0x1b)
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Get not implemented for type 0x3f
Undefined type in get_object (0x2)
WARNING: No calling convention defined for this file, analysis may be inaccurate.

=================================================================
==4170383==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbd0c in get_code_object ../librz/bin/format/pyc/marshal.c:866

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6ebf7890 in rz_list_new ../librz/util/list.c:236

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbcf0 in get_code_object ../librz/bin/format/pyc/marshal.c:865

Indirect leak of 240 byte(s) in 2 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbd0c in get_code_object ../librz/bin/format/pyc/marshal.c:866

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7faa6ee8ed37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7faa6ebf793e in rz_list_append ../librz/util/list.c:293

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6ebf7890 in rz_list_new ../librz/util/list.c:236

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7faa6ee8ef17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7faa6c0bbcf0 in get_code_object ../librz/bin/format/pyc/marshal.c:865

SUMMARY: AddressSanitizer: 504 byte(s) leaked in 9 allocation(s).
```

### Expected behavior

Memory shouldn't be leaked.

### Actual behavior

A small amount of memory is leaked.

[id 000009,sig 06,src 012103+009495,time 506124955,op splice,rep 8.gz](https://github.com/rizinorg/rizin/files/8054346/id.000009.sig.06.src.012103%2B009495.time.506124955.op.splice.rep.8.gz)

[id 000740,sig 06,src 006653,time 64579299,op havoc,rep 2.gz](https://github.com/rizinorg/rizin/files/8054345/id.000740.sig.06.src.006653.time.64579299.op.havoc.rep.2.gz)

**Comment by AKACHI-4** [comment]
can u explain a bit about it ......... ?

**Comment by ajakk** [comment]
Sure. huntr.dev released a new batch of radare2 CVEs, which were all vulnerabilities that were fuzzed out of radare2. I tested all of the inputs against Rizin, and the only impact in Rizin was these two memory leaks out of the 6 radare2 CVEs that were released.

**Comment by ajakk** [comment]
Since this is unfixed, [here's another one](https://github.com/radareorg/radare2/files/8302777/tests_65185.zip)

```
$ ./binrz/rizin/rizin -qq -AA tests_65185
WARNING: The segment 3 at 0xe8 seems to be invalid.
WARNING: Invalid strtab at 0x102f (check array failed).
WARNING: Failed to initialize section string table.
WARNING: The section 0 at 0x0 seems to be invalid.
WARNING: The section 1 at 0x158 seems to be invalid.
WARNING: The section 2 at 0x1b0 seems to be invalid.
WARNING: The section 3 at 0x348 seems to be invalid.
WARNING: The section 4 at 0x3f2 seems to be invalid.
WARNING: The section 5 at 0x140418 seems to be invalid.
WARNING: The section 6 at 0x438 seems to be invalid.
WARNING: The section 7 at 0x450 seems to be invalid.
WARNING: The section 8 at 0x4d0 seems to be invalid.
WARNING: The section 9 at 0x540 seems to be invalid.
WARNING: The section 10 at 0x650 seems to be invalid.
WARNING: The section 11 at 0xdc0 seems to be invalid.
WARNING: The section 12 at 0x71000dc8 seems to be invalid.
WARNING: The section 13 at 0xdd8 seems to be invalid.
WARNING: The section 14 at 0xfb8 seems to be invalid.
WARNING: The section 15 at 0x1000 seems to be invalid.
WARNING: The section 16 at 0x1008 seems to be invalid.
WARNING: The section 17 at 0x1008 seems to be invalid.
WARNING: The section 18 at 0x102f seems to be invalid.
WARNING: The section 19 at 0x10d8 seems to be invalid.
WARNING: The section 20 at 0x1558 seems to be invalid.
WARNING: No calling convention defined for this file, analysis may be inaccurate.

=================================================================
==2020879==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f56b0e18f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7f56b0b81a30 in rz_list_new ../librz/util/list.c:236

Indirect leak of 224 byte(s) in 4 object(s) allocated from:
    #0 0x7f56b0e18f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7f56ae95d44d in rz_search_keyword_new ../librz/search/keyword.c:21

Indirect leak of 96 byte(s) in 4 object(s) allocated from:
    #0 0x7f56b0e18d37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7f56b0b81ade in rz_list_append ../librz/util/list.c:293

Indirect leak of 17 byte(s) in 4 object(s) allocated from:
    #0 0x7f56b0e18d37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7f56ae95d4d5 in rz_search_keyword_new ../librz/search/keyword.c:28

Indirect leak of 12 byte(s) in 3 object(s) allocated from:
    #0 0x7f56b0e18d37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7f56ae95d55e in rz_search_keyword_new ../librz/search/keyword.c:35

SUMMARY: AddressSanitizer: 381 byte(s) leaked in 16 allocation(s).
```

**Comment by ajakk** [comment]
The [samples](https://drive.google.com/drive/folders/1fy6fxIxRijdK1U7GhwVNQCF-RtDa3vSQ) from [this](https://huntr.dev/bounties/47422cdf-aad2-4405-a6a1-6f63a3a93200) radare2 huntr.dev report also produce similarly small leaks (same leaks for all three samples):

```
 ~/git/rizin/build $ ./binrz/rizin/rizin -qA ~/Downloads/ne.c\(382-403\)/sample3

=================================================================
==2887582==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 176 byte(s) in 2 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb77c84ec9e in internal_ht_new ../subprojects/sdb/src/ht_inc.c:102

Direct leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb77c8510be in internal_ht_new ../subprojects/sdb/src/ht_inc.c:102

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb779ba8722 in rz_bin_ne_buf_init ../librz/bin/format/ne/ne.c:621

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb77c7d2f30 in rz_list_new ../librz/util/list.c:236

Indirect leak of 168 byte(s) in 3 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb77a59c44d in rz_search_keyword_new ../librz/search/keyword.c:21

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb77c84ed23 in internal_ht_new ../subprojects/sdb/src/ht_inc.c:109

Indirect leak of 72 byte(s) in 3 object(s) allocated from:
    #0 0x7fb77ca66d37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7fb77c7d2fde in rz_list_append ../librz/util/list.c:293

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fb77ca66f17 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5f17)
    #1 0x7fb77c851143 in internal_ht_new ../subprojects/sdb/src/ht_inc.c:109

Indirect leak of 12 byte(s) in 3 object(s) allocated from:
    #0 0x7fb77ca66d37 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libasan.so.6+0xb5d37)
    #1 0x7fb77a59c4d5 in rz_search_keyword_new ../librz/search/keyword.c:28

SUMMARY: AddressSanitizer: 788 byte(s) leaked in 18 allocation(s).
```
