### ISSUE TITLE
nullptr read in librz/bin/format/mach0/dyldcache.c:252

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2952]
Hi! We've been fuzzing your project and found the following error in `librz/bin/format/mach0/dyldcache.c:252`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

nullptr read in `librz/bin/format/mach0/dyldcache.c:252`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-sydr_724738b1dca6e92c06e702b547da6e6e1142bd66_int_overflow_48_signed`

4. You will see the following output:

```WARNING: Unknown sub-bin
WARNING: Unknown sub-bin
WARNING: Unknown sub-bin
WARNING: Unknown sub-bin
WARNING: Unknown sub-bin
WARNING: Unknown sub-bin
WARNING: Unknown sub-bin
ERROR: Unsupported slide info version 0
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2443319==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000430580 bp 0x7ffcd90b8b70 sp 0x7ffcd90b8310 T0)
==2443319==The signal is caused by a READ memory access.
==2443319==Hint: address points to the zero page.
    #0 0x430580 in strcmp (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x430580)
    #1 0xbed36a in rz_dyldcache_get_objc_opt_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/dyldcache.c:252:7
    #2 0xb0fe23 in classes /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/p/bin_dyldcache.c:376:15
    #3 0xae8457 in rz_bin_object_set_items /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:531:22
    #4 0xae706b in rz_bin_object_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:319:2
    #5 0xad7d31 in rz_bin_file_new_from_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bfile.c:150:19
    #6 0xadf3c7 in rz_bin_open_buf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:272:8
    #7 0xadec27 in rz_bin_open_io /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:330:18
    #8 0x1003353 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:727:23
    #9 0x1003353 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
    #10 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
    #11 0x7f6cf3159082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #12 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x430580) in strcmp
==2443319==ABORTING
```

**Comment by wargio** [comment]
attach the bin here so we can reproduce this.

**Comment by m4drat** [comment]
Crashing input: [crash-sydr_724738b1dca6e92c06e702b547da6e6e1142bd66_int_overflow_48_signed.zip](https://github.com/rizinorg/rizin/files/9394121/crash-sydr_724738b1dca6e92c06e702b547da6e6e1142bd66_int_overflow_48_signed.zip)
