### ISSUE TITLE
Multiple heap out-of-bounds reads of size 1 in dex.c

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2955]
Hi! We've been fuzzing your project and found the following errors in `librz/bin/format/dex/dex.c`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

Heap out-of-bounds read of size 1 in `librz/bin/format/dex/dex.c:1447` and `librz/bin/format/dex/dex.c:1495`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (1) (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-sydr_afl_s09-id_019734_time_0_execs_0_orig_id_001921_src_000769_time_1138341_execs_90700_op_havoc_rep_4_int_overflow_6_signed`

4. Execute rizin with crashing input (2):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-sydr_afl_s01-id_004538_sync_afl_main-worker_src_004167_int_overflow_21`

5. You will see the following output (for the first crashing input, the second one is similar):

```
=================================================================
==2475435==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020001aeef1 at pc 0x000000484507 bp 0x7ffc507fb900 sp 0x7ffc507fb0c0
READ of size 1 at 0x6020001aeef1 thread T0
    #0 0x484506 in strdup (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x484506)
    #1 0xba337f in rz_bin_dex_imports /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/dex/dex.c:1447:23
    #2 0xae7b56 in rz_bin_object_set_items /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:449:16
    #3 0xae706b in rz_bin_object_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:319:2
    #4 0xad7d31 in rz_bin_file_new_from_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bfile.c:150:19
    #5 0xadf3c7 in rz_bin_open_buf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:272:8
    #6 0xadec27 in rz_bin_open_io /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:330:18
    #7 0x1003353 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:727:23
    #8 0x1003353 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
    #9 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
    #10 0x7f18f2398082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #11 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

0x6020001aeef1 is located 0 bytes to the right of 1-byte region [0x6020001aeef0,0x6020001aeef1)
allocated by thread T0 here:
    #0 0x498c9d in malloc (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x498c9d)
    #1 0x4cf115 in rz_str_ndup /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/str.c:1011:14

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x484506) in strdup
Shadow bytes around the buggy address:
  0x0c048002dd80: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c048002dd90: fa fa 00 fa fa fa 00 02 fa fa 00 02 fa fa 00 06
  0x0c048002dda0: fa fa fd fa fa fa fd fa fa fa fd fd fa fa 05 fa
  0x0c048002ddb0: fa fa 05 fa fa fa 00 06 fa fa 00 06 fa fa fd fd
  0x0c048002ddc0: fa fa 00 fa fa fa 04 fa fa fa 03 fa fa fa 04 fa
=>0x0c048002ddd0: fa fa fd fa fa fa 02 fa fa fa 02 fa fa fa[01]fa
  0x0c048002dde0: fa fa 02 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048002ddf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048002de00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048002de10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048002de20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2475435==ABORTING
```

**Comment by wargio** [comment]
attach the bin here so we can reproduce this.

**Comment by m4drat** [comment]
Crashing inputs: 
1. [crash-sydr_afl_s09-id_019734_time_0_execs_0_orig_id_001921_src_000769_time_1138341_execs_90700_op_havoc_rep_4_int_overflow_6_signed.zip](https://github.com/rizinorg/rizin/files/9394092/crash-sydr_afl_s09-id_019734_time_0_execs_0_orig_id_001921_src_000769_time_1138341_execs_90700_op_havoc_rep_4_int_overflow_6_signed.zip)
 2. [crash-sydr_afl_s01-id_004538_sync_afl_main-worker_src_004167_int_overflow_21.zip](https://github.com/rizinorg/rizin/files/9394095/crash-sydr_afl_s01-id_004538_sync_afl_main-worker_src_004167_int_overflow_21.zip)
