### ISSUE TITLE
Heap out-of-bounds read in uleb128.c

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2958]
Hi! We've been fuzzing your project and found the following error in `librz/util/uleb128.c`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

Heap out-of-bounds read of size 1 in `librz/util/uleb128.c:26:7`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-a98e4cc17d380278e66cbe74cd8901b7a228bda1`

4. You will see the following output:

```
=================================================================
==2483110==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62e000047c00 at pc 0x00000139a23d bp 0x7ffc7bb90650 sp 0x7ffc7bb90648
READ of size 1 at 0x62e000047c00 thread T0
    #0 0x139a23c in rz_uleb128 /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/uleb128.c:26:7
    #1 0x13eaca0 in parse_comp_unit /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1794:9
    #2 0x13eaca0 in parse_info_raw /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1955:9
    #3 0x13eaca0 in rz_bin_dwarf_parse_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2087:9
    #4 0xfc7221 in rz_core_bin_apply_dwarf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:662:35
    #5 0xfc6039 in rz_core_bin_apply_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:281:3
    #6 0xfcc48d in rz_core_bin_apply_all_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:334:2
    #7 0x10033b0 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:735:6
    #8 0x10033b0 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
    #9 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
    #10 0x7f02d890a082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #11 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

0x62e000047c00 is located 0 bytes to the right of 47104-byte region [0x62e00003c400,0x62e000047c00)
allocated by thread T0 here:
    #0 0x498e12 in calloc (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x498e12)
    #1 0x13e9874 in get_section_bytes /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2063:13
    #2 0x13e9874 in rz_bin_dwarf_parse_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2083:13
    #3 0xfc7221 in rz_core_bin_apply_dwarf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:662:35
    #4 0xfc6039 in rz_core_bin_apply_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:281:3

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/uleb128.c:26:7 in rz_uleb128
Shadow bytes around the buggy address:
  0x0c5c80000f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c80000f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c80000f50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c80000f60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c80000f70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c5c80000f80:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c80000f90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c80000fa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c80000fb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c80000fc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c80000fd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2483110==ABORTING
```

**Comment by wargio** [comment]
attach the bin here so we can reproduce this.

**Comment by m4drat** [comment]
Crashing input: [crash-a98e4cc17d380278e66cbe74cd8901b7a228bda1.zip](https://github.com/rizinorg/rizin/files/9394081/crash-a98e4cc17d380278e66cbe74cd8901b7a228bda1.zip)
