### ISSUE TITLE
Heap out-of-bounds read in str.c

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2960]
Hi! We've been fuzzing your project and found the following error in `librz/util/str.c`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

Heap out-of-bounds read of size 6 in `librz/util/str.c:1952:9`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-690d07b7129871a1d10372c9a961ba6f684967d7`

4. You will see the following output:

```
=================================================================
==2485754==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62a00007d250 at pc 0x00000042fe66 bp 0x7ffcf0078250 sp 0x7ffcf0077a10
READ of size 6 at 0x62a00007d250 thread T0
    #0 0x42fe65 in strnlen (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x42fe65)
    #1 0x4cf109 in rz_str_nlen /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/str.c:1952:9
    #2 0x4cf109 in rz_str_ndup /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/str.c:1010:25
    #3 0x13ec311 in parse_attr_value /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1521:34
    #4 0x13ec311 in parse_die /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1731:10
    #5 0x13ec311 in parse_comp_unit /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1822:9
    #6 0x13ec311 in parse_info_raw /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1955:9
    #7 0x13ec311 in rz_bin_dwarf_parse_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2087:9
    #8 0xfc7221 in rz_core_bin_apply_dwarf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:662:35
    #9 0xfc6039 in rz_core_bin_apply_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:281:3
    #10 0xfcc48d in rz_core_bin_apply_all_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:334:2
    #11 0x10033b0 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:735:6
    #12 0x10033b0 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
    #13 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
    #14 0x7f25da294082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #15 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

0x62a00007d250 is located 0 bytes to the right of 20560-byte region [0x62a000078200,0x62a00007d250)
allocated by thread T0 here:
    #0 0x498e12 in calloc (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x498e12)
    #1 0x13e9874 in get_section_bytes /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2063:13
    #2 0x13e9874 in rz_bin_dwarf_parse_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2083:13
    #3 0xfc7221 in rz_core_bin_apply_dwarf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:662:35
    #4 0xfc6039 in rz_core_bin_apply_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:281:3

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x42fe65) in strnlen
Shadow bytes around the buggy address:
  0x0c54800079f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5480007a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5480007a10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5480007a20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5480007a30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c5480007a40: 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa
  0x0c5480007a50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5480007a60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5480007a70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5480007a80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5480007a90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2485754==ABORTING
```

**Comment by wargio** [comment]
attach the bin here so we can reproduce this.

**Comment by m4drat** [comment]
Crashing input: [crash-690d07b7129871a1d10372c9a961ba6f684967d7.zip](https://github.com/rizinorg/rizin/files/9394069/crash-690d07b7129871a1d10372c9a961ba6f684967d7.zip)

**Comment by wargio** [comment]
i cannot reproduce this. maybe i have patched it when i patched another issue related to dwarf.

**Comment by m4drat** [comment]
Just rechecked, on a clean version (https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9) the crash is still triggerable. So, yeah, looks like you've accidentally patched this bug.
