### ISSUE TITLE
Heap out-of-bounds read in coresymbolication.c

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2961]
Hi! We've been fuzzing your project and found the following error in `librz/bin/format/mach0/coresymbolication.c`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

Heap out-of-bounds read of size 25 in `librz/bin/format/mach0/coresymbolication.c:132:4`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-a120a6367e0c208ac880fee0e1798050fbe8f232`

4. You will see the following output:

```
=================================================================
==2486732==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61b000109180 at pc 0x00000042fba6 bp 0x7ffc5ee1c930 sp 0x7ffc5ee1c0f0
READ of size 25 at 0x61b000109180 thread T0
    #0 0x42fba5 in strlen (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x42fba5)
    #1 0xbf93ba in str_dup_safe_fixed /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/coresymbolication.c:132:4
    #2 0xbf93ba in rz_coresym_cache_element_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/coresymbolication.c:217:16
    #3 0xb72852 in parseDragons /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/p/bin_symbols.c:257:9
    #4 0xb72852 in load_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/p/bin_symbols.c:297:35
    #5 0xae7004 in rz_bin_object_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:300:8
    #6 0xad7d31 in rz_bin_file_new_from_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bfile.c:150:19
    #7 0xadf3c7 in rz_bin_open_buf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:272:8
    #8 0xadec27 in rz_bin_open_io /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:330:18
    #9 0x1003353 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:727:23
    #10 0x1003353 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
    #11 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
    #12 0x7f490eb13082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #13 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

0x61b000109180 is located 0 bytes to the right of 1536-byte region [0x61b000108b80,0x61b000109180)
allocated by thread T0 here:
    #0 0x498c9d in malloc (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x498c9d)
    #1 0xbf8bcb in rz_coresym_cache_element_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/coresymbolication.c:159:6

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x42fba5) in strlen
Shadow bytes around the buggy address:
  0x0c36800191e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c36800191f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3680019200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3680019210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3680019220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3680019230:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680019240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680019250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680019260: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680019270: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680019280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2486732==ABORTING
```

**Comment by wargio** [comment]
attach the bin here so we can reproduce this.

**Comment by m4drat** [comment]
Crashing input: [crash-a120a6367e0c208ac880fee0e1798050fbe8f232.zip](https://github.com/rizinorg/rizin/files/9394062/crash-a120a6367e0c208ac880fee0e1798050fbe8f232.zip)
