### ISSUE TITLE
Floating point exception and nullptr read in mach0_rebase.c

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2965]
Hi! We've been fuzzing your project and found the following errors in `librz/bin/format/mach0/mach0_rebase.c`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

Floating point exception in `librz/bin/format/mach0/mach0_rebase.c:38:48` and nullptr read in `librz/bin/format/mach0/mach0_rebase.c:44`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (1) (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-d08ad18f0d966916ce9798f0628837b5`

4. You will see the following output:

    ```
    AddressSanitizer:DEADLYSIGNAL
    =================================================================
    ==2495001==ERROR: AddressSanitizer: FPE on unknown address 0x000000c61d8b (pc 0x000000c61d8b bp 0x7ffdb8565d50 sp 0x7ffdb8565bc0 T0)
        #0 0xc61d8b in rebase_buffer_64 /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/mach0_rebase.c:38:48
        #1 0xc629cf in buf_read /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/mach0_rebase.c:188:2
        #2 0x52e6de in buf_read /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/buf.c:61:28
        #3 0x52e6de in rz_buf_read /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/buf.c:1114:16
        #4 0x52e6de in rz_buf_read_at /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/buf.c:1148:16
        #5 0xc98c83 in parse_classes_64 /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/objc/mach0_classes.c:1342:9
        #6 0xae8457 in rz_bin_object_set_items /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:531:22
        #7 0xae706b in rz_bin_object_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:319:2
        #8 0xad7d31 in rz_bin_file_new_from_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bfile.c:150:19
        #9 0xadf3c7 in rz_bin_open_buf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:272:8
        #10 0xadec27 in rz_bin_open_io /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:330:18
        #11 0x1003353 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:727:23
        #12 0x1003353 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
        #13 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
        #14 0x7f79f30f9082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
        #15 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

    AddressSanitizer can not provide additional info.
    SUMMARY: AddressSanitizer: FPE /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/mach0_rebase.c:38:48 in rebase_buffer_64
    ==2495001==ABORTING
    ```

5. Execute rizin with crashing input (2):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-4bdd112e4f67b21aa77beed6f11d4ee6`

6. You will see the following output:

    ```
    AddressSanitizer:DEADLYSIGNAL
    =================================================================
    ==2496419==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000c61edd bp 0x7fffec83c250 sp 0x7fffec83c0c0 T0)
    ==2496419==The signal is caused by a READ memory access.
    ==2496419==Hint: address points to the zero page.
        #0 0xc61edd in rebase_buffer_64 /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/mach0_rebase.c:44:22
        #1 0xc629cf in buf_read /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/mach0_rebase.c:188:2
        #2 0x52e6de in buf_read /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/buf.c:61:28
        #3 0x52e6de in rz_buf_read /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/buf.c:1114:16
        #4 0x52e6de in rz_buf_read_at /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/util/buf.c:1148:16
        #5 0xc98c83 in parse_classes_64 /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/objc/mach0_classes.c:1342:9
        #6 0xae8457 in rz_bin_object_set_items /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:531:22
        #7 0xae706b in rz_bin_object_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:319:2
        #8 0xad7d31 in rz_bin_file_new_from_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bfile.c:150:19
        #9 0xadf3c7 in rz_bin_open_buf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:272:8
        #10 0xadec27 in rz_bin_open_io /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:330:18
        #11 0x1003353 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:727:23
        #12 0x1003353 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
        #13 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
        #14 0x7f9768bd2082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
        #15 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

    AddressSanitizer can not provide additional info.
    SUMMARY: AddressSanitizer: SEGV /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/mach0/mach0_rebase.c:44:22 in rebase_buffer_64
    ==2496419==ABORTING    
    ```

**Comment by m4drat** [comment]
Here are the crashing files:
1. [crash-d08ad18f0d966916ce9798f0628837b5.zip](https://github.com/rizinorg/rizin/files/9393850/crash-d08ad18f0d966916ce9798f0628837b5.zip)
2. [crash-4bdd112e4f67b21aa77beed6f11d4ee6.zip](https://github.com/rizinorg/rizin/files/9393857/crash-4bdd112e4f67b21aa77beed6f11d4ee6.zip)
