### ISSUE TITLE
Multiple heap (stack) out-of-bounds reads in rz_endian.h

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2970]
Hi! We've been fuzzing your project and found the following errors in `librz/include/rz_endian.h`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

1. Stack out-of-bounds read of size 1 in `rz_endian.h:89:17`, Crash file: [crash-d25a5c208790bbb080868c250f4fd3bfae4ac13a.zip](https://github.com/rizinorg/rizin/files/9394375/crash-d25a5c208790bbb080868c250f4fd3bfae4ac13a.zip)

2. Stack out-of-bounds read of size 1 in `rz_endian.h:90:11`, Crash file: [crash-8a4faac995ef7962a9058c17f9da6bc5d6c77852.zip](https://github.com/rizinorg/rizin/files/9394380/crash-8a4faac995ef7962a9058c17f9da6bc5d6c77852.zip)

3. Heap out-of-bounds read of size 1 in `rz_endian.h:211:17`, Crash file: [crash-e8cf473a294a504847fb794e869ac5661794083a.zip](https://github.com/rizinorg/rizin/files/9394385/crash-e8cf473a294a504847fb794e869ac5661794083a.zip)

4. Heap out-of-bounds read of size 1 in `rz_endian.h:244`, Crash file: [crash-2aba18dee3ee0069004a3c075be116f8b9f75155.zip](https://github.com/rizinorg/rizin/files/9394387/crash-2aba18dee3ee0069004a3c075be116f8b9f75155.zip)

5. Stack out-of-bounds read of size 1 in `rz_endian.h:244`, Crash file: [crash-f3797abcb8436364760b1a751c285d02d80e961e.zip](https://github.com/rizinorg/rizin/files/9394390/crash-f3797abcb8436364760b1a751c285d02d80e961e.zip)

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input: `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-d25a5c208790bbb080868c250f4fd3bfae4ac13a`

4. You will see the following output:

    ```
    WARNING: bin_file_strings: search interval size (0xff0000000040) exeeds bin.maxstrbuf (0xa00000), skipping it.
    WARNING: bin_file_strings: search interval size (0x43000160) exeeds bin.maxstrbuf (0xa00000), skipping it.
    WARNING: bin_file_strings: search interval size (0xff0000000040) exeeds bin.maxstrbuf (0xa00000), skipping it.
    WARNING: bin_file_strings: search interval size (0x43000160) exeeds bin.maxstrbuf (0xa00000), skipping it.
    =================================================================
    ==2541802==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61700000dc70 at pc 0x0000013f2e02 bp 0x7fffdf69bdf0 sp 0x7fffdf69bde8
    READ of size 1 at 0x61700000dc70 thread T0
        #0 0x13f2e01 in rz_read_ble16 /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/include/rz_endian.h
        #1 0x13f2e01 in parse_attr_value /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1496:22
        #2 0x13f2e01 in parse_die /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1731:10
        #3 0x13f2e01 in parse_comp_unit /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1822:9
        #4 0x13f2e01 in parse_info_raw /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:1955:9
        #5 0x13f2e01 in rz_bin_dwarf_parse_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2087:9
        #6 0xfc7221 in rz_core_bin_apply_dwarf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:662:35
        #7 0xfc6039 in rz_core_bin_apply_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:281:3
        #8 0xfcc48d in rz_core_bin_apply_all_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:334:2
        #9 0x10033b0 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:735:6
        #10 0x10033b0 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
        #11 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
        #12 0x7efeb9864082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
        #13 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

    0x61700000dc70 is located 0 bytes to the right of 752-byte region [0x61700000d980,0x61700000dc70)
    allocated by thread T0 here:
        #0 0x498e12 in calloc (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x498e12)
        #1 0x13e9874 in get_section_bytes /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2063:13
        #2 0x13e9874 in rz_bin_dwarf_parse_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/dwarf.c:2083:13
        #3 0xfc7221 in rz_core_bin_apply_dwarf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:662:35
        #4 0xfc6039 in rz_core_bin_apply_info /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cbin.c:281:3

    SUMMARY: AddressSanitizer: heap-buffer-overflow /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/include/rz_endian.h in rz_read_ble16
    Shadow bytes around the buggy address:
    0x0c2e7fff9b30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x0c2e7fff9b40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x0c2e7fff9b50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x0c2e7fff9b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x0c2e7fff9b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    =>0x0c2e7fff9b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa
    0x0c2e7fff9b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c2e7fff9ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c2e7fff9bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c2e7fff9bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c2e7fff9bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    Shadow byte legend (one shadow byte represents 8 application bytes):
    Addressable:           00
    Partially addressable: 01 02 03 04 05 06 07
    Heap left redzone:       fa
    Freed heap region:       fd
    Stack left redzone:      f1
    Stack mid redzone:       f2
    Stack right redzone:     f3
    Stack after return:      f5
    Stack use after scope:   f8
    Global redzone:          f9
    Global init order:       f6
    Poisoned by user:        f7
    Container overflow:      fc
    Array cookie:            ac
    Intra object redzone:    bb
    ASan internal:           fe
    Left alloca redzone:     ca
    Right alloca redzone:    cb
    Shadow gap:              cc
    ==2541802==ABORTING
    ```

5. The remaining crashes are similar

**Comment by m4drat** [comment]
Additional crashing samples:
1. [crash-cc6879d7eaed4fa644881f861244a1b5.zip](https://github.com/rizinorg/rizin/files/9400586/crash-cc6879d7eaed4fa644881f861244a1b5.zip)
2. [crash-83c6819b9fa5818b582bd364c7c896c4dc769239.zip](https://github.com/rizinorg/rizin/files/9400590/crash-83c6819b9fa5818b582bd364c7c896c4dc769239.zip)
