### ISSUE TITLE
Use clang-format to format code and make an automatic check on PRs

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#36]

**Comment by XVilka** [comment]
Still fails due to `librz/asm/arch/tms320/c55x/table.h` file (due to inability of clang-format or meson/ninja to ignore some of the files...):
```
rizin on  clang-format [$!] took 2s 
[i] ℤ ninja -C build clang-format                                                                                                                                                                                                 14:37:56 
ninja: Entering directory `build'
[0/1] /usr/bin/meson --internal clangformat /home/user/rizin/rizin /home/user/rizin/rizin/build
Configuration file(s) do(es) not support Objective-C: /home/user/rizin/rizin/.clang-format
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.55.3', 'console_scripts', 'meson')())
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 240, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 229, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 177, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/clangformat.py", line 45, in run
    return clangformat(exelist, srcdir_name, builddir_name)
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/clangformat.py", line 33, in clangformat
    [x.result() for x in futures]
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/clangformat.py", line 33, in <listcomp>
    [x.result() for x in futures]
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/clang-format', '-style=file', '-i', '/home/user/rizin/rizin/librz/asm/arch/tms320/c55x/table.h']' returned non-zero exit status 1.
FAILED: meson-clang-format 
/usr/bin/meson --internal clangformat /home/user/rizin/rizin /home/user/rizin/rizin/build
ninja: build stopped: subcommand failed.
```
